---
- name : working with ansible
  hosts : all
  become: true
  tasks :
    - name: cleaning all
      ansible.builtin.command: yum clean all
      tags: clean
    - name : install nginx on amazon linux
      ansible.builtin.yum:
        name : nginx
        state: latest
      tags: install
    - name : start nginx
      ansible.builtin.service: 
        name : nginx
        state: started
      tags: install
    - name : enable nginx
      ansible.builtin.service: 
        name: nginx
        enabled: yes
      tags: install
    - name: stop the package
      ansible.builtin.service:
        name: nginx
        state: stopped
      tags: uninstall
    - name: remove the package
      ansible.builtin.yum:
        name: nginx
        state: absent
      tags: uninstall


