---
- name: working with ansible
  hosts: server1
  become: true
  tasks:
    - name: installing packages
      package:
        name:
          - httpd
          - nginx
          - vim
          - git
        state: present
      tags: install
    - name: update all the packages in a server
      package:
        name: "*"
        state: latest
      tags: update
    - name: delete all packages
      package:
        name:
          - httpd
          - nginx
          - vim
          - git
        state: absent
      tags: delete
